//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensor_Rotate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double frm5Portion {
            get {
                return ((double)(this["frm5Portion"]));
            }
            set {
                this["frm5Portion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unknown")]
        public global::WeifenLuo.WinFormsUI.Docking.DockState frm5DockState {
            get {
                return ((global::WeifenLuo.WinFormsUI.Docking.DockState)(this["frm5DockState"]));
            }
            set {
                this["frm5DockState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double frm5AutoDockPortion {
            get {
                return ((double)(this["frm5AutoDockPortion"]));
            }
            set {
                this["frm5AutoDockPortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double dockPanelTopPortion {
            get {
                return ((double)(this["dockPanelTopPortion"]));
            }
            set {
                this["dockPanelTopPortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double dockPanelBottomPortion {
            get {
                return ((double)(this["dockPanelBottomPortion"]));
            }
            set {
                this["dockPanelBottomPortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double dockPanelLeftPortion {
            get {
                return ((double)(this["dockPanelLeftPortion"]));
            }
            set {
                this["dockPanelLeftPortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double dockPanelRightPortion {
            get {
                return ((double)(this["dockPanelRightPortion"]));
            }
            set {
                this["dockPanelRightPortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double frm2Portion {
            get {
                return ((double)(this["frm2Portion"]));
            }
            set {
                this["frm2Portion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unknown")]
        public global::WeifenLuo.WinFormsUI.Docking.DockState frm2DockState {
            get {
                return ((global::WeifenLuo.WinFormsUI.Docking.DockState)(this["frm2DockState"]));
            }
            set {
                this["frm2DockState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double frm2AutoDockPortion {
            get {
                return ((double)(this["frm2AutoDockPortion"]));
            }
            set {
                this["frm2AutoDockPortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double frm3Portion {
            get {
                return ((double)(this["frm3Portion"]));
            }
            set {
                this["frm3Portion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unknown")]
        public global::WeifenLuo.WinFormsUI.Docking.DockState frm3DockState {
            get {
                return ((global::WeifenLuo.WinFormsUI.Docking.DockState)(this["frm3DockState"]));
            }
            set {
                this["frm3DockState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double frm3AutoDockPortion {
            get {
                return ((double)(this["frm3AutoDockPortion"]));
            }
            set {
                this["frm3AutoDockPortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double frm4Portion {
            get {
                return ((double)(this["frm4Portion"]));
            }
            set {
                this["frm4Portion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unknown")]
        public global::WeifenLuo.WinFormsUI.Docking.DockState frm4DockState {
            get {
                return ((global::WeifenLuo.WinFormsUI.Docking.DockState)(this["frm4DockState"]));
            }
            set {
                this["frm4DockState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double frm4AutoDockPortion {
            get {
                return ((double)(this["frm4AutoDockPortion"]));
            }
            set {
                this["frm4AutoDockPortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wordPName {
            get {
                return ((string)(this["wordPName"]));
            }
            set {
                this["wordPName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wordPModel {
            get {
                return ((string)(this["wordPModel"]));
            }
            set {
                this["wordPModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wordPCode {
            get {
                return ((string)(this["wordPCode"]));
            }
            set {
                this["wordPCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int wordPRange {
            get {
                return ((int)(this["wordPRange"]));
            }
            set {
                this["wordPRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wordPVoltage {
            get {
                return ((string)(this["wordPVoltage"]));
            }
            set {
                this["wordPVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wordPCurrent {
            get {
                return ((string)(this["wordPCurrent"]));
            }
            set {
                this["wordPCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wordPControler {
            get {
                return ((string)(this["wordPControler"]));
            }
            set {
                this["wordPControler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wordPAccuracy {
            get {
                return ((string)(this["wordPAccuracy"]));
            }
            set {
                this["wordPAccuracy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wordPDate {
            get {
                return ((string)(this["wordPDate"]));
            }
            set {
                this["wordPDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wordFileName {
            get {
                return ((string)(this["wordFileName"]));
            }
            set {
                this["wordFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wordFilePath {
            get {
                return ((string)(this["wordFilePath"]));
            }
            set {
                this["wordFilePath"] = value;
            }
        }
    }
}
